		$(document).ready(function(){

				load(1);
			//alert("se cargo el documento");
		

		});

	function load(page){
			var q       = $("#q").val();
			var inicio  = $("#datepicker4").val();
			var fin     = $("#datepicker5").val();
			var estatus = $("#estatus").val();
			$("#loader").fadeIn('slow');
			$.ajax({
				url:'./ajax/buscar_clientes.php?action=ajax&page='+page+'&q='+q+'&inicio='+inicio+'&fin='+fin+'&estatus='+estatus,
				 beforeSend: function(objeto){
				 $('#loader').html('<img src="./img/ajax-loader.gif"> Cargando...');
			  },
				success:function(data){
					$(".outer_div").html(data).fadeIn('slow');
					$('#loader').html('');					
				}
			})
		}


	 $( function() {
    $( "#datepicker1" ).datepicker();
  } );

	 	 $( function() {
    $( "#datepicker2" ).datepicker();
  } );

	 	 	 $( function() {
    $( "#datepicker3" ).datepicker();
  } );

	 	 	 $( function() {
    $( "#datepicker4" ).datepicker();
  } );

 	 	 	 $( function() {
    $( "#datepicker5" ).datepicker();
  } );
	
		
			function eliminar (id)
		{
			var q= $("#q").val();
		if (confirm("Realmente deseas eliminar el cliente")){	
		$.ajax({
        type: "GET",
        url: "./ajax/buscar_clientes.php",
        data: "id="+id,"q":q,
		 beforeSend: function(objeto){
			$("#resultados").html("Mensaje: Cargando...");
		  },
        success: function(datos){
		$("#resultados").html(datos);
		load(1);
		}
			});
		}
		}
		
		
// Triggered when 	..\modal\registro_clientes.php for is submitted 
$( "#guardar_cliente" ).submit(function( event ) { //cuando del form "guardar_cliente" se submmitee 
  $('#guardar_datos').attr("disabled", true);       //el boton "guardar_datos" se disable
  
 var parametros = $(this).serialize();
	 $.ajax({
			type: "POST",
			url: "ajax/nuevo_cliente.php",
			data: parametros,
			 beforeSend: function(objeto){
				$("#resultados_ajax").html("Mensaje: Cargando...");
			  },
			success: function(datos){
				//alert("Ajax success hdp");
			$("#resultados_ajax").html(datos);
			$('#guardar_datos').attr("disabled", false);
			load(1);
		  }	  
	});
  event.preventDefault();
})



$( "#editar_cliente" ).submit(function( event ) {
  $('#actualizar_datos').attr("disabled", true);
  
 var parametros = $(this).serialize();
	 $.ajax({
			type: "POST",
			url: "ajax/editar_cliente.php",
			data: parametros,
			 beforeSend: function(objeto){
				$("#resultados_ajax2").html("Mensaje: Cargando...");
			  },
			success: function(datos){
			$("#resultados_ajax2").html(datos); //after succes it is going to keep data on form
			$('#actualizar_datos').attr("disabled", false); //and button is goind to be disabled
			load(1);  //not sure why
		  }
	});
  event.preventDefault();
})


	 $( function() {
    $( "#mod_initservprof" ).datepicker();
  } );

	 	 $( function() {
    $( "#mod_finservprof" ).datepicker();
  } );

	 	 	 $( function() {
    $( "#mod_expefirma" ).datepicker();
  } );



	function obtener_datos(id){
		//getting vals from Responsive table, some of them are hidden generated by byscar.php
			var nombre_cliente = $("#nombre_cliente"+id).val();
			var initservprof = $("#initservprof_cliente"+id).val();
			var finservprof = $("#finservprof_cliente"+id).val();


			var regfiscal_cliente = $("#regimen_fiscal_cliente"+id).val();

			var contabilidad_cliente = $("#contabilidad_cliente"+id).val();

			var obligaciones_fisc_cliente = $("#obligaciones_fisc_cliente"+id).val();


			var auxiliar_cliente_cliente = $("#auxiliar_cliente_cliente"+id).val();
			var rfc_cliente_cliente = $("#rfc_cliente_cliente"+id).val();
			var contr_rfc_cliente = $("#contr_rfc_cliente"+id).val();
			var contr_efirma_cliente = $("#contr_efirma_cliente"+id).val();
			var vigencia_efirma_cliente = $("#vigencia_efirma_cliente"+id).val();
			var nrp_cliente = $("#nrp_cliente"+id).val();
			var fiel_imss_cliente = $("#fiel_imss_cliente"+id).val();
			var imss_patrones_cliente = $("#imss_patrones_cliente"+id).val();
			var infonavit_patrones_cliente = $("#infonavit_patrones_cliente"+id).val();
			var telefono_cliente = $("#telefono_cliente"+id).val();
			var email_cliente = $("#email_cliente"+id).val();
			var direccion_cliente = $("#direccion_cliente"+id).val();
			var status_cliente = $("#status_cliente"+id).val();




		//seting vals to modal edit form
			$("#mod_nombre").val(nombre_cliente);

			$("#mod_initservprof").val(initservprof);
			$("#mod_finservprof").val(finservprof);

			// Added By Jorge Manzano
			// Seleccionar los checkboxes guardados del regimen fiscal del cliente
			var array = regfiscal_cliente.split(',');
			array.forEach( function(element){
				$("#"+element+"_checkbox").prop('checked', true);
			} );


			$("#mod_contabilidad").val(contabilidad_cliente);


			$("#mod_obfiscales").val(obligaciones_fisc_cliente);
			

			$("#mod_auxiliar").val(auxiliar_cliente_cliente);
			$("#mod_rfc").val(rfc_cliente_cliente);
			$("#mod_contrdrfc").val(contr_rfc_cliente);
			$("#mod_contrefirma").val(contr_efirma_cliente);
			$("#mod_expefirma").val(vigencia_efirma_cliente);
			$("#mod_nrp").val(nrp_cliente);
			$("#mod_fielimss").val(fiel_imss_cliente);
			$("#mod_imsspatrones").val(imss_patrones_cliente);
			$("#mod_infonapatrones").val(infonavit_patrones_cliente);

			$("#mod_telefono").val(telefono_cliente);
			$("#mod_email").val(email_cliente);
			$("#mod_direccion").val(direccion_cliente);
			$("#mod_estado").val(status_cliente);
			$("#mod_id").val(id);


			//$('#mod_regfiscal').prop('checked', true);

			// alert(regfiscal_cliente);


		}
	
		
		

